import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";




const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibmplexmono-one",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "osvald::dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ibmPlexMono.className}`}>
      <Head>
      <link
        rel="icon"
        href="/icon"
        type="image/png"
        sizes="3300x2500"
      />
      </Head>
    <body>{children}</body>
    </html>
  );
}
