import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";



const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibmplexmono-one",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "osvald::dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ibmPlexMono.className}`}>
    <body>{children}</body>
    </html>
  );
}
